//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.JobPosts = new HashSet<JobPost>();
            this.PreferredCompanies = new HashSet<PreferredCompany>();
            this.UserExperiences = new HashSet<UserExperience>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public byte[] AboutCompany { get; set; }
        public string ComapnyWebsite { get; set; }
        public Nullable<System.DateTime> EstablishmentDate { get; set; }
        public string ContactPerson { get; set; }
        public string Address { get; set; }
        public Nullable<long> ContactNumber { get; set; }
        public string CompanyImage { get; set; }
        public string CompanyPresentation { get; set; }
        public string CompanyLogo { get; set; }
        public string UploadPresentation { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual IndustryType IndustryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPost> JobPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreferredCompany> PreferredCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserExperience> UserExperiences { get; set; }
    }
}
