//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobPost()
        {
            this.JobLocDets = new HashSet<JobLocDet>();
            this.JobPgDets = new HashSet<JobPgDet>();
            this.JobPostSkills = new HashSet<JobPostSkill>();
            this.JobUgDets = new HashSet<JobUgDet>();
        }
    
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int CompanyId { get; set; }
        public int RecruiterId { get; set; }
        public string Description { get; set; }
        public Nullable<int> NoOfvacancies { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Requirement { get; set; }
        public string SpecifyDoc { get; set; }
        public int IndustryId { get; set; }
        public Nullable<int> FunctionalAreaId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ExpFrom { get; set; }
        public Nullable<int> ExpTo { get; set; }
        public Nullable<decimal> CTCFrom { get; set; }
        public Nullable<decimal> CTCTo { get; set; }
        public string JobTittle { get; set; }
    
        public virtual FunctionalArea FunctionalArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobLocDet> JobLocDets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPgDet> JobPgDets { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPostSkill> JobPostSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobUgDet> JobUgDets { get; set; }
        public virtual IndustryType IndustryType { get; set; }
        public virtual Company Company { get; set; }
    }
}
