//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobUgDet
    {
        public int Id { get; set; }
        public int UgId { get; set; }
        public int JobPostId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedON { get; set; }
        public Nullable<bool> Isactive { get; set; }
    
        public virtual JobPost JobPost { get; set; }
        public virtual UG UG { get; set; }
    }
}
