//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lookout()
        {
            this.PreferredCompanies = new HashSet<PreferredCompany>();
            this.PreferredLocations = new HashSet<PreferredLocation>();
            this.WorkShifts = new HashSet<WorkShift>();
        }
    
        public int Id { get; set; }
        public int Personal_id { get; set; }
        public Nullable<int> NoticePeriod { get; set; }
        public Nullable<System.DateTime> LastWorkingDay { get; set; }
        public Nullable<bool> IsPlaced { get; set; }
        public Nullable<System.DateTime> LastActive { get; set; }
        public Nullable<decimal> Package { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreferredCompany> PreferredCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreferredLocation> PreferredLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkShift> WorkShifts { get; set; }
    }
}
