//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobPortalEntities : DbContext
    {
        public JobPortalEntities()
            : base("name=JobPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JobPostSkill> JobPostSkills { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Recruiter> Recruiters { get; set; }
        public virtual DbSet<RecruiterPlan> RecruiterPlans { get; set; }
        public virtual DbSet<RecruiterPlanDet> RecruiterPlanDets { get; set; }
        public virtual DbSet<PlanMaster> PlanMasters { get; set; }
        public virtual DbSet<FunctionalArea> FunctionalAreas { get; set; }
        public virtual DbSet<PG> PGs { get; set; }
        public virtual DbSet<UG> UGs { get; set; }
        public virtual DbSet<JobLocDet> JobLocDets { get; set; }
        public virtual DbSet<JobPgDet> JobPgDets { get; set; }
        public virtual DbSet<JobUgDet> JobUgDets { get; set; }
        public virtual DbSet<JobPost> JobPosts { get; set; }
        public virtual DbSet<Certification> Certifications { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Lookout> Lookouts { get; set; }
        public virtual DbSet<PersonalInfo> PersonalInfoes { get; set; }
        public virtual DbSet<PreferredCompany> PreferredCompanies { get; set; }
        public virtual DbSet<PreferredLocation> PreferredLocations { get; set; }
        public virtual DbSet<PremiumColldetail> PremiumColldetails { get; set; }
        public virtual DbSet<primecollege> primecolleges { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<User_type> User_type { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<UserEducation> UserEducations { get; set; }
        public virtual DbSet<UserExperience> UserExperiences { get; set; }
        public virtual DbSet<WorkShift> WorkShifts { get; set; }
        public virtual DbSet<IndustryType> IndustryTypes { get; set; }
        public virtual DbSet<JobPostActivity> JobPostActivities { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
    }
}
