//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremiumColldetail
    {
        public int id { get; set; }
        public int UserDetails_id { get; set; }
        public int UserEducation_id { get; set; }
        public int premium_id { get; set; }
    
        public virtual primecollege primecollege { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserEducation UserEducation { get; set; }
    }
}
