//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkShift
    {
        public int Id { get; set; }
        public int Shift_Id { get; set; }
        public int Lookout_Id { get; set; }
    
        public virtual Lookout Lookout { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
